service: beatlemania # the word "google" can't be in here
frameworkVersion: ">=1.6.0 <2.0.0"

provider:
  name: google
  runtime: nodejs
  project: your-project # your project on google - create this first
  # the path to the credentials file needs to be absolute
  credentials: /Users/your-username/.gcloud/creds.json # has to be full path

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  sing:
    handler: sing
    events:
      - http: sing

# you can define resources, templates etc. the same way you would in a
# Google Cloud deployment configuration
resources:
  resources:
    - type: storage.v1.bucket
      name: beatlemania-service-bucket      

      
