service: beatlemania # the word "google" can't be in here
frameworkVersion: ">=1.9.0 <2.0.0"

provider:
  name: google
  runtime: nodejs
  project: beatlemania-182023 # your project on google - create this first
  credentials: ~/.gcloud/beatlemania.json 

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  sing:
    handler: sing
    events:
      - http: sing  

      
