trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: |
    npm install -g serverless
  displayName: 'Install Serverless Framework (Ringo)'

- script: |
    npm ci
    # npm run lint
    # npm test
  workingDirectory: $(Build.SourcesDirectory)/ringo
  displayName: 'Install libraries, lint, and test (Ringo)'

- script: |
    sls deploy --stage dev --region "East US"
  workingDirectory: $(Build.SourcesDirectory)/ringo
  env:
    # Azure Service Principal
    # Values stored as secret variables
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    AZURE_TENANT_ID: $(AZURE_TENANT_ID)
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
  #condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: 'Deploy Azure Function App (Ringo)'
