trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: |
    npm install -g serverless
  displayName: 'Install Serverless Framework'

- script: |
    npm ci
    # npm run lint
    # npm test
  displayName: 'Build, Lint, and Test'

- script: |
    sls deploy --stage dev --region "East US"
  workingDirectory: $(Build.SourcesDirectory)/ringo
  env:
    # Azure Service Principal
    # Values stored as secret variables
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    AZURE_TENANT_ID: $(AZURE_TENANT_ID)
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
  displayName: 'Deploy Azure Function App (Ringo)'
