trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
- bash: |
    npm install -g serverless
  displayName: 'Install Serverless Framework'

- script: |
    npm ci
    # npm run lint
    # npm test
    # sls deploy
  displayName: 'npm install, lint, and test'
