trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: |
    npm install -g serverless
  displayName: 'Install Serverless Framework (John)'

- script: |
    npm ci
    # npm run lint
    # npm test
  workingDirectory: $(Build.SourcesDirectory)/john
  displayName: 'Install libraries, lint, and test (John)'
