service: beatlemania 
frameworkVersion: ">=1.6.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  memorySize: 512 

package:
  exclude:
    - node_modules/**
    - package.json

functions:
  sing:
    handler: handler.sing
    events:
      - http:
          path: sing
          method: get
      
